{
  "hash": "689bca8190108601b6680be2d20ff5a6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"TakeHomeExercise2\"\nauthor: \"Yao Yao\"\ndate: \"March 8, 2026\"\ndate-modified: \"last-modified\" \nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n# Prototyping Module for Visual Analytics Shiny Application\n\n## Introduction - Fintech Customer Behaviors in Colombia\nOur project dives into the Latin American fintech to understand what drives customer behavior. \n\n\nIn this prototype, I'm using Latent Class Analysis (LCA) to group customers into meaningful personas based on customer behaviors. Users should be able to actively interact with the clustering model, like adjust the number of groups or change the model’s repetitions to see how the customer segments shift. The goal is to let analysts explore their own assumptions about which customers are most loyal and which ones are on the verge of leaving the platform.\n\n## The Dataset\nWe’re using the COFINFAD dataset, which covers 48,723 customers from a major Colombian fintech firm. What makes this data special is that it combines information from different dimensions:\n- Demographics: Basic profiles like age, income, and location.\n- Product Usage: Which services they use, such as credit cards, loans, or insurance.\n- Digital Engagement: How often they log in and which app features they use.\n- Attitudinal Data: Rare metrics like NPS and satisfaction scores.\n\nBy using the customer_data.csv file, we have access to 57 variables per user. This allows our clustering model to look at a customer's entire digital and financial footprint, helping us distinguish between different groups—like \"power users\" versus \"casual spenders\".\n\n## Setting the Analytical Tools for Data Wrangling\n\nWe load the R packages using the `pacman::p_load()` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(haven, tidyverse, \n               janitor, reshape2,\n               DT, kableExtra, lubridate)\n```\n:::\n\n\n## Data Wrangling\n\n### Data source\n\nThe dataset used in the exercise is behavioral and transactional data retrieved from 48,723 customers of a Colombian fintech company, collected over 12 months from January 4, 2023, to December 29, 2023. The data is from [COFINFAD: Colombian Fintech Financial Analytics Dataset](https://data.mendeley.com/datasets/mhb4zn3258/1)\n\nFor this project, we are specifically using the `customer_data.csv` file, which aggregates 54 variables into a single record per user that's proper for LCA clustering. The raw `transactions_data.csv` (transaction level logs) will not be used. \n\n### Import data\nFirst, we import `customer_data.csv` dataset as `customer_raw_data`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncustomer_raw_data <- read_csv(\"data/customer_data.csv\",show_col_types = FALSE)\n```\n:::\n\n\n### Summary of data\nChecking the data structure in the Environment, the `customer_raw_data` has 48723 rows of 54 variables in different data types.\n\n### Check missing values\nWe first need to check the missing values as poLCA is sensitive to missing values. By checking the missing values can we decide whether it's proper to include the data into our analysis or if we need to handle it.\nBefore proceeding with the clustering, it is important to check missing values, as Latent Class Analysis (LCA) using poLCA is very sensitive to missing data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\n# Calculate count and percentage of NA values for each column\nmissing_summary <- customer_raw_data %>%\n  summarise(across(everything(), ~ sum(is.na(.)))) %>%\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"missing_count\") %>%\n  mutate(missing_percentage = (missing_count / nrow(customer_raw_data)) * 100) %>%\n  arrange(desc(missing_count))\n\n# Display variables with missing values\nprint(missing_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 54 × 3\n   variable                 missing_count missing_percentage\n   <chr>                            <int>              <dbl>\n 1 complaint_topics                 24346               50.0\n 2 credit_utilization_ratio         18263               37.5\n 3 feature_requests                 16115               33.1\n 4 customer_id                          0                0  \n 5 age                                  0                0  \n 6 gender                               0                0  \n 7 location                             0                0  \n 8 income_bracket                       0                0  \n 9 occupation                           0                0  \n10 education_level                      0                0  \n# ℹ 44 more rows\n```\n\n\n:::\n:::\n\nAs we can see in the result, complaint_topics, credit_utilization_ratio and feature_requests have missing_percentage of 50%, 37.5% and 33.1% which is quite high, we will filter these variables out from our analysis.\n\nThe result shows that several variables have high missing_percentage: complaint_topics (50.0%), credit_utilization_ratio (37.5%), and feature_requests (33.1%). We will remove these three variables together with customer_id which doesn't help in clustering, to ensure the stability and reliability of our analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_filtered <- customer_raw_data %>%\n  select(\n    # Exclude variables with high missing_percentage\n    -complaint_topics, \n    -credit_utilization_ratio, \n    -feature_requests,\n    # Exclude identifiers that don't help in clustering\n    -customer_id, \n    everything() \n  )\n```\n:::\n\n\n### 2. Filtering data/narrowing down for selected variables for our project use\nIn this step, we narrow down our dataset to the most relevant variables for clustering. Inspired by the RFM (Recency, Frequency, Monetary) framework, we transform raw date columns into meaningful behavioral metrics to enhance the model's interpretability:\n\n- Tenure (Loyalty): `user_tenure_days` is calculated as `last_tx - first_tx`, representing the total duration of the customer's active relationship with the fintech.\n- Recency (Activity): `days_since_last_tx` is calculated as the number of days between the dataset's cutoff date and the user's `last_transaction_date`. This helps identify churned vs. active users.\n\nHigh-cardinality geographic data `location` that contains special characters is removed. \n\nRedundant financial metrics `tx_count`, `avg_tx_value` are removed to prevent multicollinearity, `total_tx_volume`, `monthly_transaction_count`, `average_transaction_value`, `avg_daily_transactionsas` are also removed, as `total_transaction_volume` already serves as customer value. \n\nWe also removed some other fields including `marital_status`, `occupation`, `education_level`, `household_size` to simplify the demographic details which we will not focus in this analysis.\n\n`base_satisfaction`, `tx_satisfaction`, `product_satisfaction`, `app_store_rating` are removed as we already have `satisfaction_score` and `nps_score` 作为综合指标了.\n\n`acquisition_channel`, `resolved_tickets_ratio`, `feedback_sentiment` are removed due to they are more related to operational side but in this analysis we focus more on user value.\n\n`churn_probability` is also removed as 这是测试数据自带的预测结果。如果我们把别人已经分好的类放进聚类模型，会干扰我们自己寻找潜在类别的过程。\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lubridate) # Used for date manipulation\n\n# Assume the study cutoff date as the final day of the dataset (2023-12-29)\nstudy_cutoff_date <- as.Date(\"2023-12-29\")\n\ndf_engineered <- df_filtered %>%\n  # Convert raw character strings into Date objects (format: DD/MM/YYYY)\n  mutate(across(c(first_tx, last_tx, last_transaction_date), \n                ~ as.Date(., format = \"%d/%m/%Y\"))) %>%\n  \n  # Calculate User Tenure (Loyalty)\n  mutate(user_tenure_days = as.numeric(last_tx - first_tx)) %>%\n  \n  # Calculate Recency (Activity)\n  mutate(days_since_last_tx = as.numeric(study_cutoff_date - last_transaction_date)) %>%\n  \n  # Select final variables and drop redundant columns\n  select(\n    -marital_status, -occupation, -household_size, -gender, -location,\n    -average_transaction_value, -first_tx, -last_tx, -last_transaction_date, -first_transaction_date, -last_survey_date,    \n    -avg_daily_transactions, -total_tx_volume, -avg_tx_value, -tx_count, -transaction_frequency,\n    -base_satisfaction, -tx_satisfaction, -product_satisfaction, -app_store_rating,\n    -churn_probability, -customer_tenure,\n    -acquisition_channel, -resolved_tickets_ratio, -feedback_sentiment, -support_tickets_count, -failed_transactions, -international_transactions, -weekend_transaction_ratio\n           \n  )\n\n# Verify the updated list of variables\ncolnames(df_engineered)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"age\"                        \"income_bracket\"            \n [3] \"education_level\"            \"customer_segment\"          \n [5] \"savings_account\"            \"credit_card\"               \n [7] \"personal_loan\"              \"investment_account\"        \n [9] \"insurance_product\"          \"active_products\"           \n[11] \"app_logins_frequency\"       \"feature_usage_diversity\"   \n[13] \"bill_payment_user\"          \"auto_savings_enabled\"      \n[15] \"satisfaction_score\"         \"nps_score\"                 \n[17] \"clv_segment\"                \"monthly_transaction_count\" \n[19] \"total_transaction_volume\"   \"preferred_transaction_type\"\n[21] \"customer_lifetime_value\"    \"customer_id\"               \n[23] \"credit_utilization_ratio\"   \"feature_requests\"          \n[25] \"complaint_topics\"           \"user_tenure_days\"          \n[27] \"days_since_last_tx\"        \n```\n\n\n:::\n:::\n\n\n\n### Convert data types （包括按照 poLCA 要求将 0/1 转为 1/2，对 age, income_bracket, tx_count, total_transaction_volume 等关键指标进行科学分箱\n\n\n## Cluster Analysis\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}